-- Sable de Luz: loot. Generado por build_sableluz.py.
require "Items/ProceduralDistributions"

local LOOT = {
    { "JewelryGems", "SL.CristalKyber", 0.6 },
    { "PawnShopCases", "SL.CristalKyber", 0.4 },
    { "Antiques", "SL.CristalKyber", 0.3 },
    { "LaboratoryLockers", "SL.CristalKyber", 0.5 },
    { "UniversityStorageScience", "SL.CristalKyber", 0.3 },
    { "LaboratoryLockers", "SL.SableLuz", 0.05 },
    { "ArmyBunkerLockers", "SL.SableLuz", 0.05 },
    { "ArmyStorageGuns", "SL.SableLuz", 0.03 },
    { "PawnShopCases", "SL.SableLuz", 0.03 },
    { "LaboratoryLockers", "SL.SableLuzDoble", 0.02 },
    { "ArmyBunkerLockers", "SL.SableLuzDoble", 0.02 },
    { "JewelryGems", "SL.CristalKyber_Blue", 0.6 },
    { "PawnShopCases", "SL.CristalKyber_Blue", 0.4 },
    { "Antiques", "SL.CristalKyber_Blue", 0.3 },
    { "LaboratoryLockers", "SL.CristalKyber_Blue", 0.5 },
    { "UniversityStorageScience", "SL.CristalKyber_Blue", 0.3 },
    { "LaboratoryLockers", "SL.SableLuz_Blue", 0.05 },
    { "ArmyBunkerLockers", "SL.SableLuz_Blue", 0.05 },
    { "ArmyStorageGuns", "SL.SableLuz_Blue", 0.03 },
    { "PawnShopCases", "SL.SableLuz_Blue", 0.03 },
    { "LaboratoryLockers", "SL.SableLuzDoble_Blue", 0.02 },
    { "ArmyBunkerLockers", "SL.SableLuzDoble_Blue", 0.02 },
    { "JewelryGems", "SL.CristalKyber_Green", 0.6 },
    { "PawnShopCases", "SL.CristalKyber_Green", 0.4 },
    { "Antiques", "SL.CristalKyber_Green", 0.3 },
    { "LaboratoryLockers", "SL.CristalKyber_Green", 0.5 },
    { "UniversityStorageScience", "SL.CristalKyber_Green", 0.3 },
    { "LaboratoryLockers", "SL.SableLuz_Green", 0.05 },
    { "ArmyBunkerLockers", "SL.SableLuz_Green", 0.05 },
    { "ArmyStorageGuns", "SL.SableLuz_Green", 0.03 },
    { "PawnShopCases", "SL.SableLuz_Green", 0.03 },
    { "LaboratoryLockers", "SL.SableLuzDoble_Green", 0.02 },
    { "ArmyBunkerLockers", "SL.SableLuzDoble_Green", 0.02 },
    { "JewelryGems", "SL.CristalKyber_Purple", 0.36 },
    { "PawnShopCases", "SL.CristalKyber_Purple", 0.24 },
    { "Antiques", "SL.CristalKyber_Purple", 0.18 },
    { "LaboratoryLockers", "SL.CristalKyber_Purple", 0.3 },
    { "UniversityStorageScience", "SL.CristalKyber_Purple", 0.18 },
    { "LaboratoryLockers", "SL.SableLuz_Purple", 0.03 },
    { "ArmyBunkerLockers", "SL.SableLuz_Purple", 0.03 },
    { "ArmyStorageGuns", "SL.SableLuz_Purple", 0.018 },
    { "PawnShopCases", "SL.SableLuz_Purple", 0.018 },
    { "LaboratoryLockers", "SL.SableLuzDoble_Purple", 0.012 },
    { "ArmyBunkerLockers", "SL.SableLuzDoble_Purple", 0.012 },
    { "JewelryGems", "SL.CristalKyber_Yellow", 0.3 },
    { "PawnShopCases", "SL.CristalKyber_Yellow", 0.2 },
    { "Antiques", "SL.CristalKyber_Yellow", 0.15 },
    { "LaboratoryLockers", "SL.CristalKyber_Yellow", 0.25 },
    { "UniversityStorageScience", "SL.CristalKyber_Yellow", 0.15 },
    { "LaboratoryLockers", "SL.SableLuz_Yellow", 0.025 },
    { "ArmyBunkerLockers", "SL.SableLuz_Yellow", 0.025 },
    { "ArmyStorageGuns", "SL.SableLuz_Yellow", 0.015 },
    { "PawnShopCases", "SL.SableLuz_Yellow", 0.015 },
    { "LaboratoryLockers", "SL.SableLuzDoble_Yellow", 0.01 },
    { "ArmyBunkerLockers", "SL.SableLuzDoble_Yellow", 0.01 },
    { "JewelryGems", "SL.CristalKyber_Orange", 0.24 },
    { "PawnShopCases", "SL.CristalKyber_Orange", 0.16 },
    { "Antiques", "SL.CristalKyber_Orange", 0.12 },
    { "LaboratoryLockers", "SL.CristalKyber_Orange", 0.2 },
    { "UniversityStorageScience", "SL.CristalKyber_Orange", 0.12 },
    { "LaboratoryLockers", "SL.SableLuz_Orange", 0.02 },
    { "ArmyBunkerLockers", "SL.SableLuz_Orange", 0.02 },
    { "ArmyStorageGuns", "SL.SableLuz_Orange", 0.012 },
    { "PawnShopCases", "SL.SableLuz_Orange", 0.012 },
    { "LaboratoryLockers", "SL.SableLuzDoble_Orange", 0.008 },
    { "ArmyBunkerLockers", "SL.SableLuzDoble_Orange", 0.008 },
    { "JewelryGems", "SL.CristalKyber_White", 0.18 },
    { "PawnShopCases", "SL.CristalKyber_White", 0.12 },
    { "Antiques", "SL.CristalKyber_White", 0.09 },
    { "LaboratoryLockers", "SL.CristalKyber_White", 0.15 },
    { "UniversityStorageScience", "SL.CristalKyber_White", 0.09 },
    { "LaboratoryLockers", "SL.SableLuz_White", 0.015 },
    { "ArmyBunkerLockers", "SL.SableLuz_White", 0.015 },
    { "ArmyStorageGuns", "SL.SableLuz_White", 0.009 },
    { "PawnShopCases", "SL.SableLuz_White", 0.009 },
    { "LaboratoryLockers", "SL.SableLuzDoble_White", 0.006 },
    { "ArmyBunkerLockers", "SL.SableLuzDoble_White", 0.006 },
    { "ComicStoreCounter", "SL.SL.EmpunaduraSable", 0.4 },
    { "ElectronicStoreMisc", "SL.SL.EmpunaduraSable", 0.2 },
    { "CrateElectronics", "SL.SL.EmpunaduraSable", 0.2 },
    { "ArmyStorageElectronics", "SL.SL.EmpunaduraSable", 0.3 },
    { "LaboratoryLockers", "SL.SL.EmpunaduraSable", 0.4 },
    { "LaboratoryLockers", "SL.SL.EmpunaduraDobleSable", 0.15 },
    { "ArmyStorageElectronics", "SL.SL.EmpunaduraDobleSable", 0.1 },
    { "ComicStoreCounter", "SL.SL.EmpunaduraDobleSable", 0.1 },
}

local function addLoot()
    for _, row in ipairs(LOOT) do
        local list = ProceduralDistributions.list[row[1]]
        if list and list.items then
            table.insert(list.items, row[2])
            table.insert(list.items, row[3])
        else
            print("[SableLuz] contenedor de loot no encontrado: " .. tostring(row[1]))
        end
    end
end

Events.OnPreDistributionMerge.Add(addLoot)
